  memory check file
     320    1280   nslices   mslices    setsys
       1       2    ntypes       mnc   addtype
      -1       1    nspins    mnspin   addtype
       1       5    nparts       mnp    setsys
       2       2    ntypes       mnc   addtype
      -1       1    nspins    mnspin   addtype
       2       5    nparts       mnp    setsys
       1       3  npfilen    mpfile     addpot
     451    2995    newsz     mntab     addpot
       1       4   nlevels   mlevels  readseln
       1       4   nlevels   mlevels  readseln
       1       4   nlevels   mlevels  readseln
       1       4   nlevels   mlevels  readseln
       2       3  npfilen    mpfile     addpot
     901    2995    newsz     mntab     addpot
       1       4   nlevels   mlevels  readseln
       1       4   nlevels   mlevels  readseln
       1       4   nlevels   mlevels  readseln
       1       4   nlevels   mlevels  readseln
       3       3  npfilen    mpfile     addpot
    1351    2995    newsz     mntab     addpot
       1       4   nlevels   mlevels  readseln
       1       4   nlevels   mlevels  readseln
       1       4   nlevels   mlevels  readseln
       1       4   nlevels   mlevels  readseln
       0      10   imatnol    mmsize   smpoint
       2       4    levels   mlevels     omove
